name: Send Email Notification

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets (Without Exposing Password)
        run: |
          echo "✅ Debugging Email Configuration..."
          echo "GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}"
          echo "GMAIL_RECIPIENT: ${{ secrets.GMAIL_RECIPIENT }}"
        shell: bash

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}  # Use an App Password
          subject: "GitHub Actions Email Notification"
          from: ${{ secrets.GMAIL_USERNAME }}
          to: ${{ secrets.GMAIL_RECIPIENT }}
          secure: true
          body: "Hi, this is a GitHub Actions email notification."
