name: Debug Email Configuration

on:
  push:
    branches:
      - main

jobs:
  debug-email:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets (Without Exposing Password)
        run: |
          echo "✅ Debugging Email Configuration..."
          echo "GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}"
          echo "GMAIL_RECIPIENT: ${{ secrets.GMAIL_RECIPIENT }}"
          echo "FROM: ${{ secrets.GMAIL_USERNAME }}"  # Since 'from' is usually the same as username
        shell: bash
